// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type Platform struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Platform  string
	Password  string
	UserID    uuid.UUID
}

type User struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string
	Password  string
}
