// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: platform.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const generatePassword = `-- name: GeneratePassword :one
INSERT INTO platform (id, created_at, updated_at, platform, password, user_id)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING id, created_at, updated_at, platform, password, user_id
`

type GeneratePasswordParams struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Platform  string
	Password  string
	UserID    uuid.UUID
}

func (q *Queries) GeneratePassword(ctx context.Context, arg GeneratePasswordParams) (Platform, error) {
	row := q.db.QueryRowContext(ctx, generatePassword,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Platform,
		arg.Password,
		arg.UserID,
	)
	var i Platform
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Platform,
		&i.Password,
		&i.UserID,
	)
	return i, err
}
