name: Build and Release Easypass

on:
  push:
    tags:
      - "v*.*.*" # Triggers on tags like v1.2.3
env:
  VERSION: ${{ github.ref_name }}
  COMMIT: ${{ github.sha }}
  DATE: ${{ github.event.head_commit.timestamp }}
jobs:
  release:
    name: Build and Release ${{ matrix.arch }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux]
        arch: [amd64]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24"

      - name: Set environment variables
        run: |
          echo "GOOS=${{ matrix.goos }}" >> $GITHUB_ENV
          echo "GOARCH=${{ matrix.arch }}" >> $GITHUB_ENV
          echo "BINARY_NAME=easypass-${{ matrix.goos }}-${{ matrix.arch }}" >> $GITHUB_ENV

      - name: Set platform
        run: |
          echo "OS=$(uname | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
           echo "ARCH=$(uname -m)" >> $GITHUB_ENV
           echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
           echo "BINARY_NAME=easypass_${OS}_${ARCH}" >> $GITHUB_ENV
           echo "ARCHIVE_NAME=easypass_${OS}_${ARCH}.tar.gz" >> $GITHUB_ENV

      - name: Build Easypass binary
        run: |
          go build -ldflags "-X github.com/rpowelson12/Easypass/internal/version.Version=$VERSION" -o $BINARY_NAME ./

      - name: Create archive
        run: |
          tar -czf $ARCHIVE_NAME $BINARY_NAME

      - name: Delete existing release (if exists)
        run: |
          gh release delete "$VERSION" --yes || echo "No existing release"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub Release and upload archive
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.VERSION }}
          name: "Easypass ${{ env.VERSION }}"
          files: ${{ env.ARCHIVE_NAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
