name: Release

on:
  push:
    tags:
      - "v*.*.*" # triggers on tags like v0.2.14

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set environment variables
        run: |
          echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          echo "OS=linux" >> $GITHUB_ENV
          echo "ARCH=amd64" >> $GITHUB_ENV
          echo "BINARY_NAME=easypass" >> $GITHUB_ENV
          echo "ARCHIVE_NAME=easypass_${OS}_${ARCH}.tar.gz" >> $GITHUB_ENV

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"

      - name: Build Easypass
        run: |
          ARCHIVE_NAME="easypass_${OS}_${ARCH}.tar.gz"
          echo "Building version $VERSION"
          go build -ldflags "-X github.com/rpowelson12/Easypass/internal/version.Version=$VERSION" -o $BINARY_NAME ./
          tar -czf $ARCHIVE_NAME $BINARY_NAME
        env:
          VERSION: ${{ github.ref_name }}
          OS: linux
          ARCH: amd64
          BINARY_NAME: easypass
      - name: Package Easypass
        run: |
          tar -czf $ARCHIVE_NAME $BINARY_NAME

      - name: Delete existing release (if exists)
        run: |
          gh release delete "$VERSION" --yes || echo "No existing release"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.VERSION }}
          name: "Easypass ${{ env.VERSION }}"
          files: ${{ env.ARCHIVE_NAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
