name: Build and Release

on:
  push:
    tags:
      - "v*" # Trigger on version tags like v0.2.14

env:
  BINARY_BASE_NAME: easypass

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [linux, darwin]
        arch: [amd64, arm64]

    env:
      VERSION: ${{ github.ref_name }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23"

      - name: Build Easypass
        run: |
          echo "Building version $VERSION for ${{ matrix.os }}/ ${{ matrix.arch }}"
          BINARY_NAME="${BINARY_BASE_NAME}_${{ matrix.os }}_${{ matrix.arch }}"
          go build -ldflags "-X github.com/rpowelson12/Easypass/internal/version.Version=${VERSION}" -o $BINARY_NAME ./
          tar czf "${BINARY_NAME}.tar.gz" "$BINARY_NAME"
        shell: bash

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.VERSION }}
          name: "Easypass ${{ env.VERSION }} (${{ matrix.os }}_${{ matrix.arch }})"
          files: |
            easypass_${{ matrix.os }}_${{ matrix.arch }}
            easypass_${{ matrix.os }}_${{ matrix.arch }}.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
