name: Build and Release Easypass

on:
  push:
    tags:
      - "v*.*.*" # Triggers on tags like v1.2.3

env:
  VERSION: ${{ github.ref_name }}

jobs:
  release:
    name: Build and Release (${{ runner.os }}, ${{ matrix.arch }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux]
        arch: [amd64]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"

      - name: Set environment variables
        run: |
          echo "GOOS=${{ matrix.goos }}" >> $GITHUB_ENV
          echo "GOARCH=${{ matrix.arch }}" >> $GITHUB_ENV
          echo "BINARY_NAME=easypass-${{ matrix.goos }}-${{ matrix.arch }}" >> $GITHUB_ENV

      - name: Build Easypass
        run: |
          echo "Building version $VERSION"
          go build -ldflags "-X github.com/rpowelson12/Easypass/internal/version.Version=$VERSION" -o $BINARY_NAME ./easypass

      - name: Delete existing release (if exists)
        run: |
          gh release delete "$VERSION" --yes || echo "No existing release"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.VERSION }}
          name: "Easypass ${{ env.VERSION }}"
          files: ${{ env.BINARY_NAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
